import type { AppTemplate, TemplateCategory, TemplateFilterOption } from './types';

/**
 * 模拟的模板分类数据
 */
export const mockCategories: TemplateCategory[] = [
  {
    id: 'recommended',
    name: '推荐',
    icon: '👍',
    count: 25,
    isRecommended: true,
  },
  {
    id: 'ai_programming',
    name: 'AI 编程',
    icon: '💻',
    count: 12,
  },
  {
    id: 'knowledge_retrieval',
    name: 'Knowledge Retrieval',
    icon: '🔍',
    count: 8,
  },
  {
    id: 'research',
    name: 'Research',
    icon: '📚',
    count: 15,
  },
  {
    id: 'business_analysis',
    name: '商业数据分析',
    icon: '📊',
    count: 10,
  },
  {
    id: 'team_efficiency',
    name: '团队提效',
    icon: '⚡',
    count: 18,
  },
  {
    id: 'customer_service',
    name: '客服与运营支持',
    icon: '🎧',
    count: 14,
  },
  {
    id: 'marketing',
    name: '市场与内容营销',
    icon: '📢',
    count: 16,
  },
  {
    id: 'research_assistant',
    name: '研究助手',
    icon: '🔬',
    count: 9,
  },
];

/**
 * 模拟的模板筛选选项
 */
export const mockFilterOptions: TemplateFilterOption[] = [
  { label: '工作流', value: 'workflow', count: 15 },
  { label: 'Chatflow', value: 'chatflow', count: 20 },
  { label: '聊天助手', value: 'chat_assistant', count: 12 },
  { label: 'Agent', value: 'agent', count: 18 },
  { label: '文本生成', value: 'text_generation', count: 10 },
];

/**
 * 模拟的应用模板数据
 */
export const mockTemplates: AppTemplate[] = [
  {
    id: '1',
    name: 'DeepResearch',
    type: 'chatflow',
    description: '输入想要搜索的内容,系统就会反复执行搜索并生成报告',
    icon: '🔍',
    iconBg: '#1890ff',
    category: 'research',
    tags: ['搜索', '报告生成', 'AI'],
    createTime: '2024-01-15',
    updateTime: '2024-01-20',
    usageCount: 1250,
    rating: 4.8,
  },
  {
    id: '2',
    name: '文润·妙',
    type: 'workflow',
    description: '文润是一款基于大型英文技术文章(AI)为高质量的中文内容',
    icon: '🔥',
    iconBg: '#ff4d4f',
    category: 'ai_programming',
    tags: ['翻译', '技术文章', 'AI'],
    createTime: '2024-01-10',
    updateTime: '2024-01-18',
    usageCount: 890,
    rating: 4.6,
  },
  {
    id: '3',
    name: '文件翻译',
    type: 'chatflow',
    description: '允许您上传文件并将其翻译成任意所需语言的应用',
    icon: '📄',
    iconBg: '#52c41a',
    category: 'ai_programming',
    tags: ['文件翻译', '多语言', '上传'],
    createTime: '2024-01-12',
    updateTime: '2024-01-19',
    usageCount: 2100,
    rating: 4.7,
  },
  {
    id: '4',
    name: '跨平台文案创作',
    type: 'chatflow',
    description:
      '此聊天流程允许用户输入URL,将网页的完整文本转换为指定语气的写作风格,同时生成适用于 Instagram、X(推特)、Threads 和RED(小红书)的内容',
    icon: '✏️',
    iconBg: '#722ed1',
    category: 'marketing',
    tags: ['文案创作', '跨平台', '社交媒体'],
    createTime: '2024-01-08',
    updateTime: '2024-01-16',
    usageCount: 1560,
    rating: 4.5,
  },
  {
    id: '5',
    name: '会议纪要',
    type: 'chat_assistant',
    description: '帮你重新组织和输出混乱复杂的会议纪要',
    icon: '📋',
    iconBg: '#fa8c16',
    category: 'team_efficiency',
    tags: ['会议纪要', '组织整理', '输出'],
    createTime: '2024-01-14',
    updateTime: '2024-01-21',
    usageCount: 3200,
    rating: 4.9,
  },
  {
    id: '6',
    name: 'YouTube 频道数据分析',
    type: 'agent',
    description: '你好,告诉我您想分析的YouTube频道,我将为您整理一份完整的数据分析报告',
    icon: '📊',
    iconBg: '#13c2c2',
    category: 'business_analysis',
    tags: ['YouTube', '数据分析', '报告'],
    createTime: '2024-01-06',
    updateTime: '2024-01-17',
    usageCount: 980,
    rating: 4.4,
  },
  {
    id: '7',
    name: '客户评价处理工作流',
    type: 'workflow',
    description: '使用 LLM 分类客户的评价,将评价转发到内部系统',
    icon: '💬',
    iconBg: '#eb2f96',
    category: 'customer_service',
    tags: ['客户评价', '分类', 'LLM'],
    createTime: '2024-01-09',
    updateTime: '2024-01-15',
    usageCount: 750,
    rating: 4.3,
  },
  {
    id: '8',
    name: 'SEO 博客生成工作流',
    type: 'workflow',
    description: '从互联网上检索信息,随后分段生成SEO博客的工作流',
    icon: '⚙️',
    iconBg: '#faad14',
    category: 'marketing',
    tags: ['SEO', '博客生成', '信息检索'],
    createTime: '2024-01-11',
    updateTime: '2024-01-20',
    usageCount: 1100,
    rating: 4.6,
  },
  {
    id: '9',
    name: '科普文章作者(嵌套并行)',
    type: 'chatflow',
    description: '知乎/Quora 科普文章作者。帮助用户更快理解概念并提供学习计划',
    icon: '📖',
    iconBg: '#52c41a',
    category: 'research_assistant',
    tags: ['科普文章', '学习计划', '概念理解'],
    createTime: '2024-01-13',
    updateTime: '2024-01-22',
    usageCount: 680,
    rating: 4.5,
  },
  {
    id: '10',
    name: '个性化记忆助手',
    type: 'chatflow',
    description: '这个聊天流程受到OpenAI个性化记忆的启发,提示来自开源项目memoai',
    icon: '🧠',
    iconBg: '#722ed1',
    category: 'ai_programming',
    tags: ['个性化', '记忆', '开源'],
    createTime: '2024-01-07',
    updateTime: '2024-01-18',
    usageCount: 420,
    rating: 4.2,
  },
  {
    id: '11',
    name: '文本情感分析工作流',
    type: 'workflow',
    description: '批量识别文本中蕴含的情感,然后以JSON输出情感分类并打分',
    icon: '💖',
    iconBg: '#ff4d4f',
    category: 'business_analysis',
    tags: ['情感分析', '批量处理', 'JSON输出'],
    createTime: '2024-01-16',
    updateTime: '2024-01-23',
    usageCount: 1350,
    rating: 4.7,
  },
  {
    id: '12',
    name: 'SQL生成器',
    type: 'text_generation',
    description: '我将帮助你把自然语言转化成指定的数据库查询SQL语句,请在下方输入你需要查询的条件,并选择目标数据库类型',
    icon: '🗄️',
    iconBg: '#1890ff',
    category: 'ai_programming',
    tags: ['SQL生成', '自然语言', '数据库'],
    createTime: '2024-01-05',
    updateTime: '2024-01-19',
    usageCount: 2800,
    rating: 4.8,
  },
  {
    id: '13',
    name: '代码转换器',
    type: 'text_generation',
    description:
      '这是一个可以提供多种代码语言转换能力的应用,你可以输入你希望转换的代码片段,选择目标的代码语言,你将得到你想要的',
    icon: '🔄',
    iconBg: '#13c2c2',
    category: 'ai_programming',
    tags: ['代码转换', '多语言', '代码片段'],
    createTime: '2024-01-12',
    updateTime: '2024-01-21',
    usageCount: 1650,
    rating: 4.6,
  },
  {
    id: '14',
    name: '美股投资分析助手',
    type: 'agent',
    description: '欢迎使用您的个性化美股投资分析助手,在这里我们深入的进行股票分析,为您提供全面的洞察',
    icon: '💰',
    iconBg: '#faad14',
    category: 'business_analysis',
    tags: ['美股投资', '股票分析', '个性化'],
    createTime: '2024-01-08',
    updateTime: '2024-01-17',
    usageCount: 920,
    rating: 4.5,
  },
  {
    id: '15',
    name: '代码解释器',
    type: 'chat_assistant',
    description: '阐明代码的语法和语义',
    icon: '👁️',
    iconBg: '#722ed1',
    category: 'ai_programming',
    tags: ['代码解释', '语法', '语义'],
    createTime: '2024-01-15',
    updateTime: '2024-01-22',
    usageCount: 2100,
    rating: 4.7,
  },
  {
    id: '16',
    name: 'Jina Reader 总结网站内容',
    type: 'workflow',
    description: '使用 Jina Reader 总结爬取的网站内容',
    icon: '🌐',
    iconBg: '#52c41a',
    category: 'knowledge_retrieval',
    tags: ['网站总结', 'Jina Reader', '内容爬取'],
    createTime: '2024-01-10',
    updateTime: '2024-01-18',
    usageCount: 780,
    rating: 4.4,
  },
  {
    id: '19',
    name: '问题分类+知识库+聊天机器人',
    type: 'chatflow',
    description: '工作流基础模板,一个可以对结合知识库识别问题意图的聊天机器人',
    icon: '❓',
    iconBg: '#1890ff',
    category: 'knowledge_retrieval',
    tags: ['问题分类', '知识库', '聊天机器人'],
    createTime: '2024-01-14',
    updateTime: '2024-01-21',
    usageCount: 1200,
    rating: 4.6,
  },
  {
    id: '20',
    name: '知识库+聊天机器人',
    type: 'chatflow',
    description: '工作流基础模板,一个可以使用知识库的聊天机器人',
    icon: '💬',
    iconBg: '#13c2c2',
    category: 'knowledge_retrieval',
    tags: ['知识库', '聊天机器人', '基础模板'],
    createTime: '2024-01-09',
    updateTime: '2024-01-16',
    usageCount: 950,
    rating: 4.4,
  },
  {
    id: '21',
    name: 'research agent process flow',
    type: 'chatflow',
    description: 'Deep Research工作流,通过迭代、推理和来源,直到找到完整答案',
    icon: '⭐',
    iconBg: '#faad14',
    category: 'research',
    tags: ['深度研究', '迭代推理', '完整答案'],
    createTime: '2024-01-17',
    updateTime: '2024-01-24',
    usageCount: 580,
    rating: 4.3,
  },
];
